<?php

use Creational\ObjectPool\Car;
use Creational\ObjectPool\CarPool;
use PHPUnit\Framework\TestCase;

class ObjectPoolTest extends TestCase
{
    private $carBool;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->carBool = new CarPool();
    }

    public function testCanRentCar()
    {
        $car = $this->carBool->carUse();
        $this->assertInstanceOf(Car::class, $car);
        $this->assertEquals(1,$this->carBool->getUseCount());


    }

    public function testCanFreeCar()
    {
        $car = $this->carBool->carUse();
        $this->carBool->carFree($car);
        $this->assertEquals(1,$this->carBool->getFreeCount());
    }


}